[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/jinju"
  to = "/.netlify/functions/jinju"
  status = 200
  force = true

[[redirects]]
  from = "/_res"
  to = "/.netlify/functions/res"
  status = 200
  force = true

# XHR/Fetch 전용 프록시
[[redirects]]
  from = "/_xhr/*"
  to = "/.netlify/functions/xhr"
  status = 200
  force = true

# 우리 사이트 안에서는 프레임 허용 (임베드 차단 헤더 제거)
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self';"
